### ISSUE TITLE
ErlangString proposal

### ISSUE THREAD

**Issue by point** [appulse-projects/encon-java#12]
When `value.length() > 65535 || !is8bitString()` consider to encode such string in ErlangBinary (BINARY_EXT) rather than in list. It's way more easier to handle binaries on a erlang/elixir side. Especially when such string is somewhere inside a nested data structure.
Thanks!

**Comment by xxlabaza** [comment]
Unfortunately, I can't do it, because string serialization is strictly described [here](http://erlang.org/doc/apps/erts/erl_ext_dist.html#string_ext). 

"...implementations must ensure that lists longer than 65535 elements are encoded as LIST_EXT."

It is External Term Format reference, and I must follow it.

For your needs, you can use [Erlang.bstring](https://github.com/appulse-projects/encon-java/blob/master/encon-terms/src/main/java/io/appulse/encon/terms/Erlang.java#L240) methods. It transforms strings to ErlangBinary.

**Comment by point** [comment]
Oh, missed that.
Thanks for clarification.
